#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : tpm2-tss
Version  : 2.1.0
Release  : 1
URL      : https://github.com/tpm2-software/tpm2-tss/archive/2.1.0.tar.gz
Source0  : https://github.com/tpm2-software/tpm2-tss/archive/2.1.0.tar.gz
Summary  : TCTI library for communicating with the Microsoft TPM2 simulator.
Group    : Development/Tools
License  : BSD-2-Clause
Requires: tpm2-tss-config = %{version}-%{release}
Requires: tpm2-tss-lib = %{version}-%{release}
Requires: tpm2-tss-license = %{version}-%{release}
Requires: tpm2-tss-man = %{version}-%{release}
BuildRequires : autoconf-archive-dev
BuildRequires : doxygen
BuildRequires : libgcrypt-dev
BuildRequires : libgpg-error-dev
BuildRequires : pkgconfig(cmocka)
BuildRequires : pkgconfig(libcrypto)

%description
['![Linux Build Status](https://travis-ci.org/tpm2-software/tpm2-tss.svg?branch=master)'](https://travis-ci.org/tpm2-software/tpm2-tss)
['![Windows Build status](https://ci.appveyor.com/api/projects/status/2rdmyn1ndkiavngn?svg=true)'](https://ci.appveyor.com/project/tpm2-software/tpm2-tss)
['![Coverity Scan](https://img.shields.io/coverity/scan/3997.svg)'](https://scan.coverity.com/projects/tpm2-tss)
['![Coverage Status](https://coveralls.io/repos/github/tpm2-software/tpm2-tss/badge.svg?branch=master)'](https://coveralls.io/github/tpm2-software/tpm2-tss?branch=master)

%package config
Summary: config components for the tpm2-tss package.
Group: Default

%description config
config components for the tpm2-tss package.


%package dev
Summary: dev components for the tpm2-tss package.
Group: Development
Requires: tpm2-tss-lib = %{version}-%{release}
Provides: tpm2-tss-devel = %{version}-%{release}

%description dev
dev components for the tpm2-tss package.


%package lib
Summary: lib components for the tpm2-tss package.
Group: Libraries
Requires: tpm2-tss-license = %{version}-%{release}

%description lib
lib components for the tpm2-tss package.


%package license
Summary: license components for the tpm2-tss package.
Group: Default

%description license
license components for the tpm2-tss package.


%package man
Summary: man components for the tpm2-tss package.
Group: Default

%description man
man components for the tpm2-tss package.


%prep
%setup -q -n tpm2-tss-2.1.0

%build
## build_prepend content
./bootstrap
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1541040509
%reconfigure --disable-static --with-udevrulesdir=/usr/lib/udev/rules.d
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1541040509
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/tpm2-tss
cp LICENSE %{buildroot}/usr/share/package-licenses/tpm2-tss/LICENSE
%make_install

%files
%defattr(-,root,root,-)

%files config
%defattr(-,root,root,-)
/usr/lib/udev/rules.d/tpm-udev.rules

%files dev
%defattr(-,root,root,-)
/usr/include/tss2/tss2_common.h
/usr/include/tss2/tss2_esys.h
/usr/include/tss2/tss2_mu.h
/usr/include/tss2/tss2_sys.h
/usr/include/tss2/tss2_tcti.h
/usr/include/tss2/tss2_tcti_device.h
/usr/include/tss2/tss2_tcti_mssim.h
/usr/include/tss2/tss2_tpm2_types.h
/usr/lib64/libtss2-esys.so
/usr/lib64/libtss2-mu.so
/usr/lib64/libtss2-sys.so
/usr/lib64/libtss2-tcti-device.so
/usr/lib64/libtss2-tcti-mssim.so
/usr/lib64/pkgconfig/tss2-esys.pc
/usr/lib64/pkgconfig/tss2-mu.pc
/usr/lib64/pkgconfig/tss2-sys.pc
/usr/lib64/pkgconfig/tss2-tcti-device.pc
/usr/lib64/pkgconfig/tss2-tcti-mssim.pc
/usr/share/man/man3/ESYS_CONTEXT.3
/usr/share/man/man3/ESYS_TR.3
/usr/share/man/man3/ESYS_TR_defines.3
/usr/share/man/man3/Esys_ActivateCredential.3
/usr/share/man/man3/Esys_Certify.3
/usr/share/man/man3/Esys_CertifyCreation.3
/usr/share/man/man3/Esys_ChangeEPS.3
/usr/share/man/man3/Esys_ChangePPS.3
/usr/share/man/man3/Esys_Clear.3
/usr/share/man/man3/Esys_ClearControl.3
/usr/share/man/man3/Esys_ClockRateAdjust.3
/usr/share/man/man3/Esys_ClockSet.3
/usr/share/man/man3/Esys_Commit.3
/usr/share/man/man3/Esys_ContextLoad.3
/usr/share/man/man3/Esys_ContextSave.3
/usr/share/man/man3/Esys_Create.3
/usr/share/man/man3/Esys_CreatePrimary.3
/usr/share/man/man3/Esys_DictionaryAttackLockReset.3
/usr/share/man/man3/Esys_DictionaryAttackParameters.3
/usr/share/man/man3/Esys_Duplicate.3
/usr/share/man/man3/Esys_ECC_Parameters.3
/usr/share/man/man3/Esys_ECDH_KeyGen.3
/usr/share/man/man3/Esys_ECDH_ZGen.3
/usr/share/man/man3/Esys_EC_Ephemeral.3
/usr/share/man/man3/Esys_EncryptDecrypt.3
/usr/share/man/man3/Esys_EventSequenceComplete.3
/usr/share/man/man3/Esys_EvictControl.3
/usr/share/man/man3/Esys_FlushContext.3
/usr/share/man/man3/Esys_GetCapability.3
/usr/share/man/man3/Esys_GetCommandAuditDigest.3
/usr/share/man/man3/Esys_GetRandom.3
/usr/share/man/man3/Esys_GetSessionAuditDigest.3
/usr/share/man/man3/Esys_GetTestResult.3
/usr/share/man/man3/Esys_GetTime.3
/usr/share/man/man3/Esys_HMAC.3
/usr/share/man/man3/Esys_HMAC_Start.3
/usr/share/man/man3/Esys_Hash.3
/usr/share/man/man3/Esys_HashSequenceStart.3
/usr/share/man/man3/Esys_HierarchyChangeAuth.3
/usr/share/man/man3/Esys_HierarchyControl.3
/usr/share/man/man3/Esys_Import.3
/usr/share/man/man3/Esys_IncrementalSelfTest.3
/usr/share/man/man3/Esys_Load.3
/usr/share/man/man3/Esys_LoadExternal.3
/usr/share/man/man3/Esys_MakeCredential.3
/usr/share/man/man3/Esys_NV_Certify.3
/usr/share/man/man3/Esys_NV_ChangeAuth.3
/usr/share/man/man3/Esys_NV_DefineSpace.3
/usr/share/man/man3/Esys_NV_Extend.3
/usr/share/man/man3/Esys_NV_GlobalWriteLock.3
/usr/share/man/man3/Esys_NV_Increment.3
/usr/share/man/man3/Esys_NV_Read.3
/usr/share/man/man3/Esys_NV_ReadLock.3
/usr/share/man/man3/Esys_NV_ReadPublic.3
/usr/share/man/man3/Esys_NV_SetBits.3
/usr/share/man/man3/Esys_NV_UndefineSpace.3
/usr/share/man/man3/Esys_NV_UndefineSpaceSpecial.3
/usr/share/man/man3/Esys_NV_Write.3
/usr/share/man/man3/Esys_NV_WriteLock.3
/usr/share/man/man3/Esys_ObjectChangeAuth.3
/usr/share/man/man3/Esys_PCR_Allocate.3
/usr/share/man/man3/Esys_PCR_Event.3
/usr/share/man/man3/Esys_PCR_Extend.3
/usr/share/man/man3/Esys_PCR_Read.3
/usr/share/man/man3/Esys_PCR_Reset.3
/usr/share/man/man3/Esys_PCR_SetAuthPolicy.3
/usr/share/man/man3/Esys_PCR_SetAuthValue.3
/usr/share/man/man3/Esys_PP_Commands.3
/usr/share/man/man3/Esys_PolicyAuthValue.3
/usr/share/man/man3/Esys_PolicyAuthorize.3
/usr/share/man/man3/Esys_PolicyCommandCode.3
/usr/share/man/man3/Esys_PolicyCounterTimer.3
/usr/share/man/man3/Esys_PolicyCpHash.3
/usr/share/man/man3/Esys_PolicyDuplicationSelect.3
/usr/share/man/man3/Esys_PolicyGetDigest.3
/usr/share/man/man3/Esys_PolicyLocality.3
/usr/share/man/man3/Esys_PolicyNV.3
/usr/share/man/man3/Esys_PolicyNameHash.3
/usr/share/man/man3/Esys_PolicyNvWritten.3
/usr/share/man/man3/Esys_PolicyOR.3
/usr/share/man/man3/Esys_PolicyPCR.3
/usr/share/man/man3/Esys_PolicyPassword.3
/usr/share/man/man3/Esys_PolicyPhysicalPresence.3
/usr/share/man/man3/Esys_PolicyRestart.3
/usr/share/man/man3/Esys_PolicySecret.3
/usr/share/man/man3/Esys_PolicySigned.3
/usr/share/man/man3/Esys_PolicyTicket.3
/usr/share/man/man3/Esys_Quote.3
/usr/share/man/man3/Esys_RSA_Decrypt.3
/usr/share/man/man3/Esys_RSA_Encrypt.3
/usr/share/man/man3/Esys_ReadClock.3
/usr/share/man/man3/Esys_ReadPublic.3
/usr/share/man/man3/Esys_Rewrap.3
/usr/share/man/man3/Esys_SelfTest.3
/usr/share/man/man3/Esys_SequenceComplete.3
/usr/share/man/man3/Esys_SequenceUpdate.3
/usr/share/man/man3/Esys_SetAlgorithmSet.3
/usr/share/man/man3/Esys_SetCommandCodeAuditStatus.3
/usr/share/man/man3/Esys_SetPrimaryPolicy.3
/usr/share/man/man3/Esys_Shutdown.3
/usr/share/man/man3/Esys_Sign.3
/usr/share/man/man3/Esys_StartAuthSession.3
/usr/share/man/man3/Esys_Startup.3
/usr/share/man/man3/Esys_StirRandom.3
/usr/share/man/man3/Esys_TestParms.3
/usr/share/man/man3/Esys_Unseal.3
/usr/share/man/man3/Esys_Vendor_TCG_Test.3
/usr/share/man/man3/Esys_VerifySignature.3
/usr/share/man/man3/Esys_ZGen_2Phase.3
/usr/share/man/man3/Tss2_Tcti_Device_Init.3
/usr/share/man/man3/Tss2_Tcti_Mssim_Init.3

%files lib
%defattr(-,root,root,-)
/usr/lib64/libtss2-esys.so.0
/usr/lib64/libtss2-esys.so.0.0.0
/usr/lib64/libtss2-mu.so.0
/usr/lib64/libtss2-mu.so.0.0.0
/usr/lib64/libtss2-sys.so.0
/usr/lib64/libtss2-sys.so.0.0.0
/usr/lib64/libtss2-tcti-device.so.0
/usr/lib64/libtss2-tcti-device.so.0.0.0
/usr/lib64/libtss2-tcti-mssim.so.0
/usr/lib64/libtss2-tcti-mssim.so.0.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/tpm2-tss/LICENSE

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man7/tss2-tcti-device.7
/usr/share/man/man7/tss2-tcti-mssim.7
